DROP TABLE BJ_USER_DETAILS;
DROP TABLE BJ_USER_LOGIN_HISTORY;
 
CREATE TABLE BJ_USER_DETAILS (
  ID INT NOT NULL,
  USER_ID VARCHAR(15) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);
 
CREATE TABLE BJ_USER_LOGIN_HISTORY (
  ID INT NOT NULL,
  STATUS VARCHAR(15) NOT NULL,
  SESSION_ID INT DEFAULT NULL,
  LOGIN_TIME TIMESTAMP DEFAULT NULL,
  LOGOUT_TIME TIMESTAMP DEFAULT NULL,
  USER_ID INT DEFAULT NULL,
  PRIMARY KEY (ID)
);

insert into bj_user_details values (1, 'admin', 'admin');
commit;

select * from BJ_USER_DETAILS;
select * from BJ_USER_LOGIN_HISTORY;


CREATE SEQUENCE BJ_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10

delete from BJ_USER_LOGIN_HISTORY; commit;
