CREATE TABLE USER_DETAILS (
  ID INT NOT NULL,
  USER_ID VARCHAR(15) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);
 
CREATE TABLE USER_LOGIN_HISTORY (
  ID INT NOT NULL AUTO_INCREMENT,
  STATUS VARCHAR(15) NOT NULL,
  SESSION_ID LONG NULL,
  LOGIN_TIME TIMESTAMP,
  LOGOUT_TIME TIMESTAMP,
  USER_ID INT NULL,
  PRIMARY KEY (ID)
);

insert into user_details values (1, 'admin', 'admin');

select * from USER_DETAILS;
select * from USER_LOGIN_HISTORY;

DROP TABLE USER_DETAILS;
DROP TABLE USER_LOGIN_HISTORY;

delete from USER_LOGIN_HISTORY;